services:
  db:
    image: mysql
    container_name: db_dogs
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dogs
    volumes:
      - local_mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql-phpmyadmin
    
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "81:80"
    networks:
      - mysql-phpmyadmin


volumes:
  local_mysql:    

networks:
  mysql-phpmyadmin:

# Pour lancer les caontainer
# docker-compose up -d