services:
  db:
    image: mysql
    container_name: db_hopital
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hopital
    volumes:
      - local_mysql_exo4:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "80:80"
    networks:
      - mysql-phpmyadmin


volumes:
  local_mysql_exo4:

networks:
  mysql-phpmyadmin:

# Pour lancer les containers
# docker-compose up -d