services:
  db:
    image: mysql
    container_name: db_todo
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo
    volumes:
      - local_mysql_todo:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "80:80"
    networks:
      - mysql-phpmyadmin
volumes:
  local_mysql_todo:

networks:
  mysql-phpmyadmin:

# Pour lancer les containers
# docker-compose up -d